### ISSUE TITLE
Contributions not allowed

### ISSUE THREAD

**Issue by davehamber** [xuedi/xuedi#5]
`12:24:03.645: [xuedi] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/fix-everything:fix-everything --set-upstream
remote: Permission to xuedi/xuedi.git denied to davehamber.
fatal: unable to access 'https://github.com/xuedi/xuedi.git/': The requested URL returned error: 403`

**How disappointing.**

**Comment by xuedi** [comment]
fixed by adding you two :-)
